services: 
  web: 
    build:
      context: app
      dockerfile: Dockerfile
    env_file: 
      - ./app/.env
    environment:
      - APP_PORT=${APP_PORT}
    ports: 
      - '${APP_PORT}:${APP_PORT}'